server:
  port: 80


spring:
  application:
    name: cloud-order-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册新选 默认是true,单节点无所谓，集群必须设置为ture配合ribbon使用负载均衡
    fetch-registry: true
    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #单机注册
      #defaultZone: http://localhost:7001/eureka/
      #集群注册
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true
#