server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
#cansul注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      #  instance-id: ${spring.application.name}:${server.port}
      #hostname: 127.0.0.1