server:
  port: 80


spring:
  application:
    name: cloud-order-service


eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册新选 默认是true,单节点无所谓，集群必须设置为ture配合ribbon使用负载均衡
    fetch-registry: true
    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #单机注册
      #defaultZone: http://localhost:7001/eureka/
      #集群注册
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
